---
name: Pandora's Box
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      runner:
        description: The runner to execute on
        default: "ubuntu-latest"
        type: choice
        options:
          - ubuntu-latest
          - devnet
          - testnet
      environment:
        description: The environment to run against
        required: false
        type: environment
      transaction_count:
        default: "10000"
        description: The number of transactions to send
        type: string
      transaction_batch:
        default: "100"
        description: The transaction batch size
        type: string
      mode:
        default: "EOA"
        description: The mode for the stress test
        type: choice
        options:
          - EOA
          - ERC20
          - ERC721
  workflow_call:
    inputs:
      transaction_count:
        required: true
        description: The number of transactions to send
        type: string
      transaction_batch:
        required: true
        description: The transaction batch size
        type: string
      environment:
        description: The environment to run against
        type: string
        required: true
      runner:
        required: true
        type: string
        description: The runner label to use
      mode:
        required: true
        description: The mode for the stress test
        type: string
    secrets:
      PANDORAS_TARGET:
        required: true
      PANDORAS_MNEMONIC:
        required: true

jobs:
  open_pandoras_box:
    name: Open Pandora's Box
    concurrency: ${{ inputs.environment }}_performance
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout Pandora's Box Repository
        uses: actions/checkout@v3
        with:
          repository: trapesys/pandoras-box
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Prepare Pandora's Box
        run: |
          npm install -g yarn
          yarn install && yarn build && yarn link
          echo "$HOME/.yarn/bin" >> $GITHUB_PATH
      - name: Install JQ
        run: |
          mkdir -p $HOME/.local/bin
          curl -sLo $HOME/.local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x $HOME/.local/bin/jq
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - id: pandora
        name: Open Pandora's Box
        run: |
          pandoras-box -url ${{ secrets.PANDORAS_TARGET }} --mode "${{ inputs.mode }}" -m "${{ secrets.PANDORAS_MNEMONIC }}" -b ${{ inputs.transaction_batch }} -t ${{ inputs.transaction_count }} -o pandorasConsequences.json
          echo "name=tps::$(cat pandorasConsequences.json | jq -r '.averageTPS')" >> $GITHUB_OUTPUT
      - name: Archive Pandora's Consequences
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: pandoras-consequences-report
          path: pandorasConsequences.json
