---
name: Release
on: # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"
      # to be used by fork patch-releases ^^
      - "v*.*.*-*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.x

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "name=tag_name::${TAG}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Run GoReleaser
        run: |
          docker run \
          		--rm \
          		--privileged \
          		-e CGO_ENABLED=1 \
          		-e GITHUB_TOKEN \
          		-e DOCKER_USERNAME \
          		-e DOCKER_PASSWORD \
          		-v /var/run/docker.sock:/var/run/docker.sock \
          		-v `pwd`:/go/src/$(PACKAGE_NAME) \
          		-w /go/src/$(PACKAGE_NAME) \
          		ghcr.io/goreleaser/goreleaser-cross:${GOLANG_CROSS_VERSION} \
          		--rm-dist --skip-validate
        env:
          PACKAGE_NAME: github.com/mauricio-b-r/polygon-edge
          GOLANG_CROSS_VERSION: v1.18.3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
